name: "Hello World"
description: "Greet someone and record the time"
inputs:
    removePreviousSwarmSecrets:
        description: boolean
        required: true
    swarmSecretsPrefix:
        default: SWARM_
        required: true
    sshServerAddress:
        required: true
    sshServerPort:
        required: true
    sshServerUsername:
        required: true
    secretsJson:
        description: secrets to be created in targeted docker swarm. comes from ${{ toJson(secrets) }} or an input json.
        required: true
runs:
    using: "node20"
    main: "dist/index.js"
