name: "Hello World"
description: "Greet someone and record the time"
inputs:
    milliseconds: # id of input
        description: "time to wait"
        required: true
        default: '10000'
outputs:
    time: # id of output
        description: "The time we greeted you"
runs:
    using: "node20"
    main: "dist/index.js"
