name: "Secret creator"
description: "Creates docker swarm secrets through an ssh connection."

inputs:
    swarm-secrets-prefix:
        description: string
        default: SWARM_
        required: true
    ssh-server-address:
        description: string
        required: true
    ssh-server-port:
        description: string
        required: true
    ssh-server-username:
        description: string
        required: true
    ssh-server-password:
        description: string
        required: true
    secrets-json:
        description: "secrets to be created in targeted docker swarm. Secrets must be named snake case."
        required: false

runs:
    using: "node20"
    main: "dist/index.js"
