on: 
    workflow_dispatch:
    push:

jobs:
  wait_job:
    runs-on: ubuntu-latest

    name: A job to wait

    steps:
        - uses: actions/checkout@v4
        
        - 
            name: Waiter action step
            uses: ./ # Uses an action in the root directory
            with:
                removePreviousSwarmSecrets: ''
                swarmSecretsPrefix: ''
                sshServerAddress: ''
                sshServerPort: ''
                sshServerUsername: ''
                secretsJson: ''
